#! /bin/sh
# sxhkd &

# Start session for polkit an etc
lxsession &

# Launch the topbar
~/.config/polybar/launch.sh

# set background
sh .fehbg

# Fix mouse pointer being a cross
xsetroot -cursor_name left_ptr

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color \#f2777a
bspc config click_to_focus true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

